import React from 'react';
import { ButtonToolbar, ButtonGroup, Button } from 'react-bootstrap';

export default function ScaleSelectionComponent({ changeScale, song }) {
	function _handleSelect(event) {
		event.preventDefault();
		const scale = event.target.value.split(',');
		changeScale(scale, song);
	}

	// need to update song to match the current scale

	return (
		<div className="Scales">
			<ButtonToolbar>
				<ButtonGroup>
					<Button
						value={[
							'A5',
							'G#5',
							'F#5',
							'E5',
							'D5',
							'C#5',
							'B4',
							'A4',
							'G#4',
							'F#4',
							'E4',
							'D4',
							'C#4',
							'B3',
							'A3'
						]}
						onClick={_handleSelect}>
						A
					</Button>
					<Button
						value={[
							'B5',
							'A#5',
							'G#5',
							'F#5',
							'E5',
							'D#5',
							'C#5',
							'B4',
							'A#4',
							'G#4',
							'F#4',
							'E4',
							'D#4',
							'C#4',
							'B3'
						]}
						onClick={_handleSelect}>
						B
					</Button>
					<Button
						value={[
							'C5',
							'B4',
							'A4',
							'G4',
							'F4',
							'E4',
							'D4',
							'C4',
							'B3',
							'A3',
							'G3',
							'F3',
							'E3',
							'D3',
							'C3'
						]}
						onClick={_handleSelect}>
						C
					</Button>
					<Button
						value={[
							'D5',
							'C#5',
							'B4',
							'A4',
							'G4',
							'F#4',
							'E4',
							'D4',
							'C#4',
							'B3',
							'A3',
							'G3',
							'F#3',
							'E3',
							'D3'
						]}
						onClick={_handleSelect}>
						D
					</Button>
					<Button
						value={[
							'E5',
							'D#5',
							'C#5',
							'B4',
							'A4',
							'G#4',
							'F#4',
							'E4',
							'D#4',
							'C#4',
							'B3',
							'A3',
							'G#3',
							'F#3',
							'E3'
						]}
						onClick={_handleSelect}>
						E
					</Button>
					<Button
						value={[
							'F5',
							'E5',
							'D5',
							'C5',
							'Bb4',
							'A4',
							'G4',
							'F4',
							'E4',
							'D4',
							'C4',
							'Bb3',
							'A3',
							'G3',
							'F3'
						]}
						onClick={_handleSelect}>
						F
					</Button>
					<Button
						value={[
							'G5',
							'F#5',
							'E5',
							'D5',
							'C5',
							'B4',
							'A4',
							'G4',
							'F#4',
							'E4',
							'D4',
							'C4',
							'B3',
							'A3',
							'G3'
						]}
						onClick={_handleSelect}>
						G
					</Button>
				</ButtonGroup>
			</ButtonToolbar>
			<ButtonToolbar>
				<ButtonGroup>
					<Button
						value={[
							'A5',
							'G5',
							'F5',
							'E5',
							'D5',
							'C5',
							'B4',
							'A4',
							'G4',
							'F4',
							'E4',
							'D4',
							'C4',
							'B3',
							'A3'
						]}
						onClick={_handleSelect}>
						Am
					</Button>
					<Button
						value={[
							'B5',
							'A5',
							'G5',
							'F#5',
							'E5',
							'D5',
							'C#5',
							'B4',
							'A4',
							'G4',
							'F#4',
							'E4',
							'D4',
							'C#4',
							'B3'
						]}
						onClick={_handleSelect}>
						Bm
					</Button>
					<Button
						value={[
							'C5',
							'Bb4',
							'Ab4',
							'G4',
							'F4',
							'Eb4',
							'D4',
							'C4',
							'Bb3',
							'Ab3',
							'G3',
							'F3',
							'Eb3',
							'D3',
							'C3'
						]}
						onClick={_handleSelect}>
						Cm
					</Button>
					<Button
						value={[
							'D5',
							'C5',
							'Bb4',
							'A4',
							'G4',
							'F4',
							'E4',
							'D4',
							'C4',
							'Bb3',
							'A3',
							'G3',
							'F3',
							'E3',
							'D3'
						]}
						onClick={_handleSelect}>
						Dm
					</Button>
					<Button
						value={[
							'E5',
							'D5',
							'C5',
							'B4',
							'A4',
							'G4',
							'F#4',
							'E4',
							'D4',
							'C4',
							'B3',
							'A3',
							'G3',
							'F#3',
							'E3'
						]}
						onClick={_handleSelect}>
						Em
					</Button>
					<Button
						value={[
							'F5',
							'Eb5',
							'Db5',
							'C5',
							'Bb4',
							'Ab4',
							'G4',
							'F4',
							'Eb4',
							'Db4',
							'C4',
							'Bb3',
							'Ab3',
							'G3',
							'F3'
						]}
						onClick={_handleSelect}>
						Fm
					</Button>
					<Button
						value={[
							'G5',
							'F5',
							'Eb5',
							'D5',
							'C5',
							'Bb4',
							'A4',
							'G4',
							'F4',
							'Eb4',
							'D4',
							'C4',
							'Bb3',
							'A3',
							'G3'
						]}
						onClick={_handleSelect}>
						Gm
					</Button>
				</ButtonGroup>
			</ButtonToolbar>
		</div>
	);
}
